
package com.mycompany.jirex;

/**
 *
 * @author CL3-PC29
 */
public class Jirexes extends javax.swing.JFrame {

    public Jirexes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JLabel();
        txtName3 = new javax.swing.JLabel();
        txtName4 = new javax.swing.JLabel();
        txtName5 = new javax.swing.JLabel();
        txtName6 = new javax.swing.JLabel();
        txtName7 = new javax.swing.JLabel();
        txtName8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        txtName9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("nb.versioning.conflicted.color"));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setText("Address");
        txtName.setOpaque(true);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        jTextField1.setText("Last Name");
        jTextField1.setOpaque(true);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, -1));

        jButton1.setText("Register");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Student Registration Form");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 320, 60));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel3.setText("Role No:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel4.setText("Student Name:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel5.setText("Father Name:");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        jLabel8.setText("Date Of Birth");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txtName1.setText("Mobile Number:");
        txtName1.setOpaque(true);
        getContentPane().add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        txtName2.setText("Email Id:");
        txtName2.setOpaque(true);
        getContentPane().add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        txtName3.setText("Password:");
        txtName3.setOpaque(true);
        getContentPane().add(txtName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        txtName4.setText("Gender:");
        txtName4.setOpaque(true);
        getContentPane().add(txtName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        txtName5.setText("Department:");
        txtName5.setOpaque(true);
        getContentPane().add(txtName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        txtName6.setText("Course");
        txtName6.setOpaque(true);
        getContentPane().add(txtName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        txtName7.setText("Student Photo:");
        txtName7.setOpaque(true);
        getContentPane().add(txtName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        txtName8.setText("No file chosen");
        txtName8.setOpaque(true);
        getContentPane().add(txtName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 90, 20));

        jTextField2.setText("Year");
        jTextField2.setOpaque(true);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 110, -1));

        jTextField3.setText("First Name");
        jTextField3.setOpaque(true);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        jTextField4.setOpaque(true);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 250, 90));

        jTextField5.setOpaque(true);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 190, -1));

        jTextField6.setText("+91");
        jTextField6.setOpaque(true);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 50, -1));

        jTextField7.setText("Month");
        jTextField7.setOpaque(true);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 50, -1));

        jTextField8.setText("Day");
        jTextField8.setOpaque(true);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 50, -1));

        jTextField9.setOpaque(true);
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, -1));

        jTextField10.setOpaque(true);
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 250, -1));

        jTextField11.setOpaque(true);
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 250, -1));

        jTextField13.setOpaque(true);
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 250, -1));

        jRadioButton1.setText("Male");
        jRadioButton1.setOpaque(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 80, -1));

        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(true);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jCheckBox2.setText("ACT");
        jCheckBox2.setOpaque(true);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 50, -1));

        jCheckBox3.setText("CT");
        jCheckBox3.setOpaque(true);
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 40, -1));

        jCheckBox4.setText("HM");
        jCheckBox4.setOpaque(true);
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 50, -1));

        jCheckBox5.setText("BSOA");
        jCheckBox5.setOpaque(true);
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 60, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setOpaque(true);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 250, 20));

        jPasswordField1.setOpaque(true);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 250, -1));

        jButton2.setText("Choose File");
        jButton2.setOpaque(true);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        txtName9.setText("City:");
        txtName9.setOpaque(true);
        getContentPane().add(txtName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Jirexes().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

 
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Jirexes().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtName1;
    private javax.swing.JLabel txtName2;
    private javax.swing.JLabel txtName3;
    private javax.swing.JLabel txtName4;
    private javax.swing.JLabel txtName5;
    private javax.swing.JLabel txtName6;
    private javax.swing.JLabel txtName7;
    private javax.swing.JLabel txtName8;
    private javax.swing.JLabel txtName9;
    // End of variables declaration//GEN-END:variables
}
