
import javax.swing.JOptionPane;
/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CL3-PC30
 */
public class tikctacktoo extends javax.swing.JFrame {

    /**
     * Creates new form tikctacktoo
     */
    public tikctacktoo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player2 = new javax.swing.JTextField();
        three = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        one = new javax.swing.JTextField();
        two = new javax.swing.JTextField();
        six = new javax.swing.JTextField();
        four = new javax.swing.JTextField();
        five = new javax.swing.JTextField();
        nine = new javax.swing.JTextField();
        seven = new javax.swing.JTextField();
        eight = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player2.setText("0");
        player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ActionPerformed(evt);
            }
        });
        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 110, -1));

        three.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 70, 60));

        jLabel1.setText("Player1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setText("Player 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        player1.setText("0");
        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, -1));

        one.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 60));

        two.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 70, 60));

        six.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, 60));

        four.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 60));

        five.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 70, 60));

        nine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 70, 60));

        seven.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, 60));

        eight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, 60));

        jButton10.setText("Check");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int playerOne = Integer.parseInt(player1.getText());
        int playerTwo = Integer.parseInt(player2.getText());
        
        int scorePlayerOne = playerOne + 1;
        int scorePlayerTwo = playerTwo + 1;
        
        
        int num1 = Integer.parseInt(one.getText());
        int num2 = Integer.parseInt(two.getText());
        int num3 = Integer.parseInt(three.getText());
        int num4 = Integer.parseInt(four.getText());
        int num5 = Integer.parseInt(five.getText());
        int num6 = Integer.parseInt(six.getText());
        int num7 = Integer.parseInt(seven.getText());
        int num8 = Integer.parseInt(eight.getText());
        int num9 = Integer.parseInt(nine.getText());
        
        if (num1 == 0 && num4 == 0 && num7 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        } else if ( num2 == 0 && num5 == 0 && num8 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        }else if ( num3 == 0 && num6 == 0 && num9 == 0) {
           scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        } else if ( num1 == 0 && num2 == 0 && num3 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        }else if ( num4 == 0 && num5 == 0 && num6 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        }else if ( num7 == 0 && num8 == 0 && num9 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        }else if ( num1 == 0 && num5 == 0 && num9 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        }else if ( num3 == 0 && num5 == 0 && num7 == 0) {
            scorePlayerOne = scorePlayerOne +1;
            player1.setText(""+ scorePlayerOne);
        } else if (num1 == 1 && num4 == 1 && num7 == 1) {
            scorePlayerTwo = scorePlayerTwo + 1;
            player1.setText(""+ scorePlayerOne);
        } else if ( num2 == 1 && num5 == 1 && num8 == 1) {
            scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        }else if ( num3 == 1 && num6 == 1 && num9 == 1) {
           scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        } else if ( num1 == 1 && num2 == 1 && num3 == 1) {
            scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        }else if ( num4 == 1 && num5 == 1 && num6 == 1) {
            scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        }else if ( num7 == 1 && num8 == 1 && num9 == 1) {
            scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        }else if ( num1 == 1 && num5 == 1&& num9 == 1) {
            scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        }else if ( num3 == 1 && num5 == 1 && num7 == 1) {
            scorePlayerTwo = scorePlayerTwo +1;
            player1.setText(""+ scorePlayerTwo);
        }
        
        if (playerOne == 5) {
            JOptionPane.showMessageDialog(null, "Player 1 win");
        }
        
        if (playerTwo == 5) {
            JOptionPane.showMessageDialog(null, "Player 2 win");
        }

        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tikctacktoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tikctacktoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tikctacktoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tikctacktoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tikctacktoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eight;
    private javax.swing.JTextField five;
    private javax.swing.JTextField four;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nine;
    private javax.swing.JTextField one;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JTextField seven;
    private javax.swing.JTextField six;
    private javax.swing.JTextField three;
    private javax.swing.JTextField two;
    // End of variables declaration//GEN-END:variables
}
